# --- CONFIGURACIÓN DE SUPABASE ---
[supabase]
SUPABASE_URL = "https://fquudfxkybqylcgtbbin.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdXVkZnhreWJxeWxjZ3RiYmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNjE4MDYsImV4cCI6MjA3OTgzNzgwNn0.Wf5i2KEvzWXj3dwsY5HxBOp3AcOX82h6WytZ0bH3dHg"
# --- CONFIGURACIÓN DE CLOUDINARY ---
[cloudinary]
cloud_name = "dvnlaqqhf"
api_key = "221773451257883"
api_secret = "PIQDvp4Jbfvp0Ov1ZKC1xcSHol4"
# --- CONFIGURACIÓN DE TELEGRAM ---
[telegram]
token = "8382805163:AAHFklVKQZtFUblLfefnXsAfWYfPq6KK1As"
